import dash

import dash_bootstrap_components as dbc
from dash import html, dcc, callback, Input, Output, dash_table

import plotly.express as px

import pandas as pd

# autogenerated title and link but we also can set a path, title, and link name on our own:
dash.register_page(__name__,
                   path='/',
                   title='Homepage of Synkyndineo',
                   name='Homepage of Synkyndineo',
                   order=1)


"""
Colourpicker:
"""

"""
https://encycolorpedia.de/708090
"""

colors = {
    'dark-blue-grey' : 'rgb(62, 64, 76)',
    'medium-blue-grey' : 'rgb(77, 79, 91)',
    'superdark-green' : 'rgb(41, 56, 55)',
    'white': 'rgb(251, 251, 252)',
    'light-grey' : 'rgb(208, 206, 206)',
    'slate-grey': '#5c6671',
    'slate-grey-invertiert': '#a3998e',
    'slate-grey-darker': '#4b5259',
    'dusk-white': '#CFCFCF',
    'back-white': '#F7F7F7',
    'anthrazitgrau': '#373f43',
    'invertiert': '#c8c0bc'

}


def layout():
    """
    Use functions to get reusable code:

    Page layouts must be defined with a variable or function called layout.
    When creating an app with Pages, only use app.layout in your main app.py file.
    :return:
    """

    image_path = {'spx_tnx': 'assets/spx_vs_tnx_nov23.PNG',
                  'crown_shyness': 'assets/crown_shyness_rain_forest_canopy_malaysia_deed_3572010709_120c0dda13_o.jpg',
                  'flock_birds': 'assets/Taking_evasive_action_-_geograph.org.uk_-_1069344.jpg',
                  }

    layout_home = dbc.Container([
                     dbc.Row([
                        dbc.Col([], width=1),
                        dbc.Col([
                            html.H3(children='Homepage: Ideas, notions, news...',
                                    style={'textAlign': 'center'}),
                            html.Br(),
                            html.Hr(),
                            html.Img(src=image_path['spx_tnx'],
                                     style={'box-shadow': '8px 8px 10px 8px dodgerBlue',
                                            'display': 'block', 'margin-left': 'auto', 'margin-right': 'auto',
                                            'width': '50%'},),
                            html.Br(),
                            html.Hr(),
                        ], width=10),
                        dbc.Col([], width=1),
                        ]),

                    dbc.Row([
                        dbc.Col([], width=1),
                        dbc.Col([
                            html.Br(),
                            html.Hr(),
                            html.Img(src=image_path['crown_shyness'],
                                     style={'box-shadow': '8px 8px 10px 8px dodgerBlue',
                                            'display': 'block', 'margin-left': 'auto', 'margin-right': 'auto',
                                            'width': '80%'},
                                     title='Rain forest canopy, Malaysia',
                                     role="heading",
                                     alt='Rain forest canopy, Malaysia von flickrfavorites, href="/photos/38485387@N02/3572010709/in/album-72157618991243924/"'),
                            html.Br(),
                            html.Hr(),
                        ], width=5),
                        dbc.Col([
                            html.Br(),
                            html.Hr(),
                            html.Img(src=image_path['flock_birds'],
                                     style={'box-shadow': '8px 8px 10px 8px dodgerBlue',
                                            'display': 'block', 'margin-left': 'auto', 'margin-right': 'auto',
                                            'width': '80%'},
                                     alt='https: // commons.wikimedia.org / wiki / File: Taking_evasive_action_ - _geograph.org.uk_ - _1069344.jpg',
                                     title='Flock of birds taking evasive action'
                                     ),
                            html.Br(),
                            html.Hr(),
                        ], width=5),
                        dbc.Col([], width=1),
                    ]),
                    ])

    return layout_home
